{
 "title": "Compute Prometheus Gauge",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Protected Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twistlock_protected_containers", "legendFormat": "protected_containers" }
   ]
  },
  {
   "title": "Active Defenders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_active_defenders{job=\"twistlock\"}",
     "legendFormat": "active_defenders"
    }
   ]
  },
  {
   "title": "Total Defenders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_total_defenders{job=\"twistlock\"}",
     "legendFormat": "total_defenders"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_images_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "critical_vulns"
    },
    {
     "expr": "twistlock_images_high_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "high_vulns"
    },
    {
     "expr": "twistlock_images_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "medium_vulns"
    },
    {
     "expr": "twistlock_images_low_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "low_vulns"
    }
   ]
  },
  {
   "title": "Host Vulnerabilities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_hosts_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "critical_vulns"
    },
    {
     "expr": "twistlock_hosts_high_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "high_vulns"
    },
    {
     "expr": "twistlock_hosts_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "medium_vulns"
    },
    {
     "expr": "twistlock_hosts_low_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "low_vulns"
    }
   ]
  },
  {
   "title": "Serverless Vulnerabilities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_serverless_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "critical_vulns"
    },
    {
     "expr": "twistlock_serverless_high_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "high_vulns"
    },
    {
     "expr": "twistlock_serverless_critical_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "medium_vulns"
    },
    {
     "expr": "twistlock_serverless_low_vulnerabilities{job=\"twistlock\"}",
     "legendFormat": "low_vulns"
    }
   ]
  },
  {
   "title": "WAAS Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(twistlock_container_app_firewall_events{job=\"twistlock\"}[5m]))",
     "legendFormat": "container_waas_events"
    },
    {
     "expr": "sum(irate(twistlock_host_app_firewall_events{job=\"twistlock\"}[5m]))",
     "legendFormat": "host_waas_events"
    }
   ]
  },
  {
   "title": "Resource Compliance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_critical_compliance{job=\"twistlock\"}",
     "legendFormat": "critical_compliance"
    },
    {
     "expr": "twistlock_high_compliance{job=\"twistlock\"}",
     "legendFormat": "high_compliance"
    },
    {
     "expr": "twistlock_critical_compliance{job=\"twistlock\"}",
     "legendFormat": "medium_compliance"
    },
    {
     "expr": "twistlock_low_compliance{job=\"twistlock\"}",
     "legendFormat": "low_compliance"
    }
   ]
  },
  {
   "title": "Access Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_access_events{job=\"twistlock\"}",
     "legendFormat": "access_events"
    }
   ]
  },
  {
   "title": "Runtime Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "twistlock_container_runtime_events{job=\"twistlock\"}",
     "legendFormat": "container_runtime"
    },
    {
     "expr": "twistlock_host_runtime_events{job=\"twistlock\"}",
     "legendFormat": "host_runtime"
    }
   ]
  },
  {
   "title": "WAAS Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_container_app_firewalls{job=\"twistlock\"}",
     "legendFormat": "container_waas"
    }
   ]
  },
  {
   "title": "WAAS Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twistlock_host_app_firewalls{job=\"twistlock\"}",
     "legendFormat": "host_waas"
    }
   ]
  }
 ]
}