#!/bin/sh

# api url for the console found here https://prisma.pan.dev/api/cloud/api-urls
PC_APIURL=""
PC_ACCESSKEY=""
PC_SECRETKEY=""

# api url found in the Enterprise edition under compute > manage > system > utilities > path to console
TL_CONSOLE=""

# If using the Enterprise edition just use the access key from above
TL_USER=""

# If using the Enterprise edition just use the secret key from above
TL_PASSWORD=""
